'use client';
import { useEffect, useState } from 'react';
import Link from 'next/link';
import Image from 'next/image';

type Guard = { mode: string; warningEndsAt?: string | null; message?: string };
export default function ServiceConsole() {
  const [authorized, setAuthorized] = useState(false), [passcode, setPasscode] = useState(''), [state, setState] = useState<Guard | null>(null), [message, setMessage] = useState(''), [status, setStatus] = useState('');
  const load = async () => { const r = await fetch('/api/service-guard/control', { cache: 'no-store' }); if (r.ok) { setAuthorized(true); setState(await r.json()); } };
  useEffect(() => { void load(); }, []);
  const login = async (e: React.FormEvent) => { e.preventDefault(); setStatus('Checking…'); const r = await fetch('/api/service-guard/auth', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ passcode }) }); const d = await r.json(); if (r.ok) { setPasscode(''); setAuthorized(true); setStatus(''); await load(); } else setStatus(d.message || 'Access denied'); };
  const act = async (action: string) => { if ((action === 'lock' || action === 'activate') && !confirm(`Switch the public site to ${action === 'lock' ? 'engineering/service' : 'active'} mode?`)) return; setStatus('Updating…'); const r = await fetch('/api/service-guard/control', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ action, message }) }); const d = await r.json(); if (r.ok) { setState(d); setStatus('Mode updated and audited.'); } else setStatus(d.message || 'Update failed'); };
  return <main className="owner-console"><section><div className="owner-console__brand"><Image src="/macsunny-logo.png" alt="" width={96} height={96} sizes="96px"/><div><span>Restricted engineering access</span><h1>Site Service Console</h1></div></div>{!authorized ? <form onSubmit={login}><label htmlFor="owner-passcode">Owner/developer passcode</label><input id="owner-passcode" type="password" autoComplete="current-password" value={passcode} onChange={e => setPasscode(e.target.value)} required /><button>Unlock console</button></form> : <div><div className="owner-console__status"><span>Current mode</span><strong>{state?.mode || 'Loading…'}</strong>{state?.warningEndsAt && <small>Deadline: {new Date(state.warningEndsAt).toLocaleString()}</small>}</div><label htmlFor="service-message">Optional public service note</label><textarea id="service-message" maxLength={280} value={message} onChange={e => setMessage(e.target.value)} placeholder="Expected completion or support note"/><div className="owner-console__actions"><button onClick={() => act('activate')}>Set active</button><button onClick={() => act('warn')}>Start 7-day warning</button><button className="danger" onClick={() => act('lock')}>Enable service mode</button></div></div>}<p className="owner-console__message" role="status">{status}</p><Link href="/">Return to storefront</Link></section></main>;
}
